### ISSUE TITLE
Questions about working with the image

### ISSUE THREAD

**Issue by nkborisov** [varghes/Raspberry-QNX#1]
Hello

First of all, let me thank you for your work! I would ask you about some details.Has that image of QNX support for HDMI output or i should work with the board by the RS-232 interface? Have you testing that image with RPi Zero (it has BCM2835 onboard also)?

**Comment by varghes** [comment]
though it supports HDMI ,use RS-232/ USB-UART  .  I have not checked on RPi Zero board ,but it should should work there also.

**Comment by demitov** [comment]
Thank you very much for your work.
I'm using SDP 6.6 on Windows 7 and the following appears when I build it:


```
make[1]: Entering directory `C:/Users/demitov/ide-5.0-workspace/Bsp_Rasp/images'
mkifs -r../install  bcm2835.build ifs-bcm2835.bin
Line 46: Host file 'raw.boot' not available.
make[1]: *** [ifs-bcm2835.bin] Error 1
make[1]: Leaving directory `C:/Users/demitov/ide-5.0-workspace/Bsp_Rasp/images'
make: *** [images] Error 2
```

How to fix it?

**Comment by varghes** [comment]
hi,
I guess "armle" , is not supported under qnx6.6 ... check  the equivalent folder for this "C:\QNX650\target\qnx6\armle"  in 6.6 ,  the file points to  " C:\QNX650\target\qnx6\armle\boot\sys\boot.raw", So either you have to change the .build to armle-v7 and give a try or open a armle-v or use any [armv7] 6.6 code , and make the relevant changes in startup & serial driver.

**Comment by SergiuJec** [comment]
hello,
will it run on raspberry pi 3?
Thanks

**Comment by varghes** [comment]
No . it won't , Pi 3 Architecture is different .  I am planning to add that support .

**Comment by bcahuzac1** [comment]
Hi,
any improvement for RPI3. 
if you haven't done it yet, i would like to try can you can tell me briefly which files can be found for the BSP (prebuilt and src folder) ? I suppose that hardware startup and driver could be found somewhere for example.

and which one usually need to be updated for BSP to works with QNX ?
Best

**Comment by varghes** [comment]
No not yet done ,  stuck with uboot.  To make the kernel run ,you have to modify the startup file , configure the timer , uart & interrupt . Other drivers you can add as per your wish .
