### ISSUE TITLE
won't boot

### ISSUE THREAD

**Issue by Akiruoss** [varghes/Raspberry-QNX#3]
Hello
I've copied working_images files into my sdcard 
power my raspberry pi but on the screen it's stuck on 
## Starting application at 0x00200000 ##

Regards
Aki

**Comment by varghes** [comment]
it works only on https://www.raspberrypi.org/products/raspberry-pi-1-model-b-plus/ ..  , which hardware are u using ?

**Comment by Akiruoss** [comment]
hello and thankyou for your reply
i'm using this one

https://www.sparkfun.com/products/retired/11546

Il giorno mar 12 feb 2019 alle ore 18:02 Varghese Alphonse <
notifications@github.com> ha scritto:

**Comment by marvinyane** [comment]
Hi, my RSP B+ wont boot too.
 
- At first, copied all files in working_image  to /dev/sdx1(FAT16), but Green Led blink in 8 flashs, which means too old start* and bootcode.bin. 
- So, changed to new version start.elf and  bootcode.bin, now uboot can boot normally. 

```
-Boot 2016.09-rc1-g8097d58 (Aug 31 2017 - 11:52:20 -0700)

DRAM:  128 MiB
RPI: Board rev 0x3 unknown
RPI Unknown model (0x900032)
boot regs: 0x00000000 0x00000000 0x00000000 0x00000000
MMC:   bcm2835_sdhci: 0
reading uboot.env

** Unable to read "uboot.env" from mmc0:1 **
Using default environment

In:    serial
Out:   lcd
Err:   lcd
Net:   Net Initialization Skipped
No ethernet found.
starting USB...
USB0:   Core Release: 2.80a
scanning bus 0 for devices... 3 USB Device(s) found
       scanning usb for storage devices... 0 Storage Device(s) found
       scanning usb for ethernet devices... 
Error: sms0 address not set.
Warning: failed to set MAC address
1 Ethernet Device(s) found
Hit any key to stop autoboot:  0 
switch to partitions #0, OK
mmc0 is current device
Scanning mmc 0:1...
Found U-Boot script /boot.scr
reading /boot.scr
128 bytes read in 9 ms (13.7 KiB/s)
## Executing script at 02000000
reading ifs-bcm2835.bin
44501704 bytes read in 3062 ms (13.9 MiB/s)
## Starting application at 0x00200000 ...�B��������(��������쥥�������쬍���������X�
                                                                                     X��杍���O�������������F�������������������������B���$�����������������������B���D���約��
                                                                                                                                                                               �֎����޵۝�鬴����������Ԗ��̴����������m������B��������������
     �䵤������B�����
```

**Comment by varghes** [comment]
Rpi3 support not added,  rpi3 uses different interrupt ip + memory mapping is different. This works only on rpi 1. Plans are there to support other boards also

**Comment by marvinyane** [comment]
> Rpi3 support not added, rpi3 uses different interrupt ip + memory mapping is different. This works only on rpi 1. Plans are there to support other boards also

Sorry for mistake spell， I use RPI1 B+ to test it.

**Comment by varghes** [comment]
U-Boot 2016.09-rc1-g8097d58 (Aug 31 2017 - 11:52:20 -0700)

DRAM:  448 MiB
RPI Model B+ (0x10)
boot regs: 0x00000000 0x00000000 0x00000000 0x00000000
MMC:   bcm2835_sdhci: 0
reading uboot.env

** Unable to read "uboot.env" from mmc0:1 **
Using default environment

In:    serial
Out:   lcd
Err:   lcd
Net:   Net Initialization Skipped
No ethernet found.
starting USB...
USB0:   Core Release: 2.80a
scanning bus 0 for devices... 3 USB Device(s) found
       scanning usb for storage devices... 0 Storage Device(s) found
       scanning usb for ethernet devices... 1 Ethernet Device(s) found
Hit any key to stop autoboot:  0
switch to partitions #0, OK
mmc0 is current device
Scanning mmc 0:1...
Found U-Boot script /boot.scr
reading /boot.scr
128 bytes read in 12 ms (9.8 KiB/s)
## Executing script at 02000000
reading ifs-bcm2835.bin
44501704 bytes read in 3038 ms (14 MiB/s)
## Starting application at 0x00200000 ...

PIO init :
CPU0: Dcache: 512x32 WB
CPU0: Icache: 512x32
CPU0: VFP 410120b5
CPU0: 410fb767: arm1176 rev 7 700MHz
Loading IFS...done
elf_map: 1M va=fe000000 pa=00200000 sz=00100000
elf_map: 1M va=fe000000 pa=00200000 sz=00100000
Header size=0x0000009c, Total Size=0x00000520, #Cpu=1, Type=4
Section:system_private offset:0x000001c8 size:0x00000068
  syspage ptr user:fc404000 kernel:fc404000
  cpupage ptr user:fc4048a0 kernel:fc4048a0 spacing:84
  kdebug info:00000000 callback:00000000
  boot pgms: idx=0
    0) base paddr:00213000 start addr:fe04604c
  ramsize:00000000 pagesize:00001000
Section:qtime offset:0x00000148 size:0x00000060
  boot:00000000 CPS:00000000000f4240 rate/scale:1000000000/-15 intr:3
  flags:00000000 load:0 epoch:1970 rr_mul:0 adj count/inc:0/0
Section:callout offset:0x000000a0 size:0x00000048
  reboot:fc404710 power:00000000
  timer_load:fc404734 reload:fc404760 value:fc4047a0
  0) display:fc4047c0 poll:fc4047e4 break:fc404808
  1) display:00000000 poll:00000000 break:00000000
Section:cpuinfo offset:0x000001a8 size:0x00000020
  0) cpu:410fb767 flags:c0000006 speed:000002bc cache i/d:1/0 name:45
Section:cacheattr offset:0x000004e0 size:0x00000040
  0) flags:32 size:0020 #lines:0200 control:fc404520 next:255
  1) flags:11 size:0020 #lines:0200 control:fc404588 next:255
Section:meminfo offset:0x00000520 size:0x00000000
Section:asinfo offset:0x000002e0 size:0x000001c0
  0000) 0000000000000000-00000000ffffffff o:ffff a:0010 p:100 c:00000000 n:21
  0020) 0000000000000000-00000000ffffffff o:0000 a:0010 p:100 c:00000000 n:28
  0040) 0000000000200000-00000000101fffff o:0020 a:0017 p:100 c:00000000 n:36
  0060) 0000000000000000-00000000ffffffff o:ffff a:0010 p:100 c:00000000 n:21
  0080) 0000000000200000-00000000101fffff o:0060 a:0007 p:100 c:00000000 n:40
  00a0) 000000000020f110-0000000002c70ac7 o:0000 a:0005 p:100 c:00000000 n:53
  00c0) 0000000000200008-000000000020f10f o:0000 a:0007 p:100 c:00000000 n:61
  00e0) 000000000020f110-0000000002c70ac7 o:0000 a:0007 p:100 c:00000000 n:69
  0100) 0000000000000000-00000000ffffffff o:ffff a:0010 p:100 c:00000000 n:77
  0120) 00000000fe014000-00000000fe090fcc o:0100 a:0000 p:100 c:00000000 n:85
  0140) 0000000000200000-0000000000200007 o:0040 a:0007 p:100 c:00000000 n:91
  0160) 0000000002c70ac8-0000000002c7afff o:0040 a:0007 p:100 c:00000000 n:91
  0180) 0000000002c838f4-0000000002dcffff o:0040 a:0007 p:100 c:00000000 n:91
  01a0) 0000000002fd0000-00000000101fffff o:0040 a:0007 p:100 c:00000000 n:91
Section:hwinfo offset:0x000002b8 size:0x00000028
  0) size:3 tag:3(Group) isize:3, iname:0(hw), owner:65535, kids:1
  12) size:3 tag:17(Bus) isize:3, iname:9(unknown), owner:0, kids:0
Section:typed_strings offset:0x00000230 size:0x00000020
  off:0 type:5 string:'UNKNOWN'
  off:12 type:2 string:'localhost'
Section:strings offset:0x00000250 size:0x00000068
  [0]'hw' [3]'Group' [9]'unknown' [17]'Bus' [21]'memory' [28]'below4G'
  [36]'ram' [40]'1to1' [45]'arm1176' [53]'imagefs' [61]'startup' [69]'bootram'
  [77]'virtual' [85]'vboot' [91]'sysram'
Section:intrinfo offset:0x000004a0 size:0x00000040
  0) vector_base:00000000, #vectors:64, cascade_vector:7fffffff
     cpu_intr_base:00000000, cpu_intr_stride:0, flags:0000
      id => flags:8000, size:0068, rtn:fc4045d0
     eoi => flags:9000, size:0048, rtn:fc404638
     mask:fc404680, unmask:fc4046c8, config:00000000
Section:smp offset:0x00000520 size:0x00000000
Section:pminfo offset:0x00000520 size:0x00000000
Section:mdriver offset:0x00000520 size:0x00000000
Section:boxinfo offset:0x00000520 size:0x00000000
Section:cpu offset:0x00000128 size:0x00000020
  page_flush:fc404594 page_flush_deferred:fc4045c8
  upte_ro:00000a2e upte_rw:0000083e
  kpte_ro:0000021e kpte_rw:0000001e
  mask_nc:0000000c
  ttb_attr:00000010 pte_attr=00000009
  mmu_cr1:00051878 set:00e0387f clr:00000300 -> 00e5387f
Jumping to QNX

System page at phys:02c83000 user:fc404000 kern:fc404000
Starting next program at vfe04604c
cpu_startnext: cpu0 -> fe04604c
Welcome to QNX Neutrino 6.5 on the Raspberry pi
Starting slogger and pipe servers...
Starting DBGU driver...
opening ...
Serial opened...
Starting graphics driver
Starting Touchscreen driver...
Init over...
# ls
.ph     dev     lib     tmmp    usr
bin     etc     proc    tmp     var
#

**Comment by varghes** [comment]
I tried checking the same with few SD cards .. 8GB/strontium, 32/16GB/HP, 16GB/SanDisk  all works fine. I use Windows OS formatting tool , fat32 /32kb unit size..

**Comment by marvinyane** [comment]
Hi,

After change bootcode.bin/start* to git@github.com:raspberrypi/firmware.git  tag : 1.20160620,  the issue fixed, QNX has boot up normally.

**Comment by varghes** [comment]
thats great ..

**Comment by VictorGoiano** [comment]
Hello

First of all, let me congratulate for your work! I only have RPI Model B, it's very similar to yours, how can i get a working image for this hardware? Could you give me some tips?

**Comment by varghes** [comment]
> Hello
> 
> First of all, let me congratulate for your work! I only have RPI Model B, it's very similar to yours, how can i get a working image for this hardware? Could you give me some tips?

Copy the   "Raspberry-QNX/working_image/"   files to FAT formatted SD card & boot the Raspberry PI .. To access the QNX shell connect USB-UART to Raspberry  &use  PUTTY tool
